const API='http://localhost:8000';
const $=id=>document.getElementById(id); const state=[];
async function call(path,options={}){const r=await fetch(API+path,{...options,credentials:'include'});const d=await r.json();if(!r.ok)throw Error(d.detail||'Apex AI could not complete that request.');return d}
function suggest(text){$('question').value=text;$('question').focus()}
function newChat(){$('messages').innerHTML='<div class="empty" id="empty"><div class="brand" style="justify-content:center;font-size:34px"><span class="brand-mark">⌁</span></div><h1>How can Apex AI help?</h1><p>Ask a question, or give Apex a document to understand.</p></div>';state.length=0}
async function login(){/* Login is available through the API docs until the full auth screen is connected. */}
async function upload(){const input=$('file');if(!input.files[0])return;const form=new FormData();form.append('file',input.files[0]);$('status').textContent='Processing document…';try{const d=await call('/api/documents',{method:'POST',body:form});$('status').textContent=`${d.filename} is ${d.status}. You can ask about it now.`}catch(e){$('status').textContent=e.message}}
async function ask(){const box=$('question'),text=box.value.trim();if(!text)return;const empty=$('empty');if(empty)empty.remove();$('messages').insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHtml(text)}</div><div class="bubble ai" id="pending">Apex AI is thinking…</div>`);box.value='';$('messages').scrollTop=$('messages').scrollHeight;try{const d=await call('/api/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text})});$('pending').textContent=d.answer;(d.citations||[]).forEach(c=>$('pending').insertAdjacentHTML('beforeend',`<div class="source">[${c.number}] ${escapeHtml(c.source)}, page ${c.page}</div>`));state.push({question:text,answer:d.answer});$('history').textContent=state.map(x=>x.question).join('\n')}catch(e){$('pending').textContent=e.message}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function logout(){try{await call('/api/auth/logout',{method:'POST'})}finally{location.href='index.html'}}
$('question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}});
